from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from models import Advisory

def generate_advisory_pdf(advisory: Advisory) -> BytesIO:
    """Generate a technical threat bulletin in PDF format."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=18)
    styles = getSampleStyleSheet()
    
    # Custom styles
    header_style = ParagraphStyle(
        'HeaderStyle',
        parent=styles['Heading1'],
        fontSize=18,
        textColor=colors.HexColor("#1e293b"),
        spaceAfter=12
    )
    
    sub_header_style = ParagraphStyle(
        'SubHeaderStyle',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor("#2563eb"),
        spaceBefore=12,
        spaceAfter=6
    )

    elements = []

    # Title
    elements.append(Paragraph(f"SecureEye Cyber Intelligence Bulletin", header_style))
    elements.append(Paragraph(f"Subject: {advisory.title}", styles['Heading3']))
    elements.append(Spacer(1, 12))

    # Metadata Table
    data = [
        ["Field", "Value"],
        ["CVE ID(s)", ", ".join(advisory.cve_ids or ["N/A"])],
        ["Severity", str(advisory.severity.value).upper()],
        ["CVSS Score", str(advisory.cvss_score or "N/A")],
        ["Sector", advisory.sector.name if advisory.sector else "General"],
        ["Published", str(advisory.published_at or advisory.created_at)[:16]],
    ]
    t = Table(data, colWidths=[100, 350])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (1, 0), colors.HexColor("#f1f5f9")),
        ('TEXTCOLOR', (0, 0), (1, 0), colors.HexColor("#1e293b")),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor("#e2e8f0")),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 24))

    # Executive Summary
    elements.append(Paragraph("Executive Summary", sub_header_style))
    elements.append(Paragraph(advisory.ai_summary or "No AI summary available for this advisory.", styles['BodyText']))
    elements.append(Spacer(1, 12))

    # Technical Details
    elements.append(Paragraph("Technical Intelligence", sub_header_style))
    elements.append(Paragraph(advisory.description or "No description provided.", styles['BodyText']))
    elements.append(Spacer(1, 12))

    # Mitigation
    elements.append(Paragraph("Remediation Strategy", sub_header_style))
    elements.append(Paragraph(advisory.mitigation or "Vendor patches and network isolation recommended.", styles['BodyText']))
    
    # Footer
    elements.append(Spacer(1, 48))
    elements.append(Paragraph("-" * 80, styles['BodyText']))
    elements.append(Paragraph("Generated by SecureEye Threat Intelligence Platform", styles['Italic']))

    doc.build(elements)
    buffer.seek(0)
    return buffer
